### ISSUE TITLE
Shale fails to distinguish itself appropriately as a fork

### ISSUE THREAD

**Issue by kaniini** [ShaleCoders/shaleservices#1]
Shale is presently incompatible with Atheme's license for branding materials, and therefore *undistributable in present form*.  The guidelines for downstream forks very clearly explains what forks are required to do to be compliant:

> To people looking to fork, we suggest these guidelines in order for your fork to be legally compliant (of course, we ask that you do not consider this as formal legal advice):
>
> Rebrand atheme to ensure that your fork is not misrepresented as an official Atheme release. To do so:
> 1. Change all references of 'atheme' in configure.ac and handle_admin().
> 2. Rerun autogen.sh.
> 3. Modify libathemecore/version.c to denote that this is no longer Atheme. We ask that you keep the Atheme credits in place, however the license does not require this.
> 4. Ideally replace references to atheme.conf and atheme.motd as well.
> Maintain code contributions to your forks under the same license as Atheme itself so that they may be shared amongst the larger Atheme community.
> Keep Atheme copyright notices in place where relevant.
> Allow the greater Atheme community to engage your project so that you get important and critical bug fixes ahead of public release.

None of these steps have been followed, please take corrective actions so we will not have to escalate the situation, thank you.

**Comment by ShaleCoders** [comment]
Hello,

I'm currently not near a computer to fix this, i'll be back in the office monday and will fix this

many thanks
Tony

**Comment by kaniini** [comment]
Hello,

Thank you for your response.  I am glad to hear it.

**Comment by ShaleCoders** [comment]
Hello,

Please can you confirm this has been resolved. 

Thanks
Tony

**Comment by kaniini** [comment]
Seems fine now.  Thanks.
